import type {
  Project,
  Skill,
  StatItem,
  NavItem,
  Certification,
  ExperienceItem,
  ToolPill,
} from './types';

// ─── Navigation ──────────────────────────────────────────────────────────────
export const NAV_ITEMS: NavItem[] = [
  { label: 'Work', href: '#work' },
  { label: 'Skills', href: '#skills' },
  { label: 'About', href: '#about' },
  { label: 'Contact', href: '#contact' },
];

// ─── Stats ───────────────────────────────────────────────────────────────────
export const STATS: StatItem[] = [
  { value: '40K+', label: 'Training samples', numericValue: 40, suffix: 'K+' },
  { value: '0.94', label: 'F1-Score', numericValue: 0.94 },
  { value: '5+', label: 'Brands managed', numericValue: 5, suffix: '+' },
  { value: '3+', label: 'Full-stack apps', numericValue: 3, suffix: '+' },
];

// ─── Projects (completed) ────────────────────────────────────────────────────
export const PROJECTS: Project[] = [
  {
    id: 'fake-news-detector',
    num: '01',
    title: 'Fake News Detector',
    description:
      'End-to-end NLP classifier trained on 40K samples. TF-IDF + Logistic Regression hitting 0.94 F1. Flask REST API with 6 endpoints, a JavaScript frontend for real-time prediction, and a TinyLlama layer that explains its own decisions.',
    tags: ['NLP', 'Machine Learning', 'Flask', 'LLM'],
    tech: 'Python · Scikit-learn · TF-IDF · LIME · Ollama',
    category: 'ml',
    github: 'https://github.com/namanrai1222',
    status: 'completed',
  },
  {
    id: 'nexus-forum',
    num: '02',
    title: 'Nexus Forum Platform',
    description:
      'Reddit-inspired from scratch. Authentication, threaded comments, upvote system, user profiles, role-based admin panel for moderation. Zero frameworks — pure PHP routing.',
    tags: ['Full Stack', 'PHP', 'Community'],
    tech: 'PHP · JavaScript · HTML/CSS',
    category: 'fullstack',
    github: 'https://github.com/namanrai1222',
    status: 'completed',
  },
  {
    id: 'auto-saas-builder',
    num: '03',
    title: 'Auto SaaS Builder',
    description:
      'Four-layer architecture: orchestrator → scheduler → agents → services. Multi-tenant environment config, CI/CD via GitHub Actions, automated deployment pipeline.',
    tags: ['Automation', 'Node.js', 'DevOps'],
    tech: 'Node.js · Axios · GitHub Actions',
    category: 'automation',
    github: 'https://github.com/namanrai1222',
    status: 'completed',
  },
  {
    id: 'indevaa-crm',
    num: '04',
    title: 'Indevaa Lead Pipeline',
    description:
      'Apify-powered scraping system that reduced manual prospecting by 60%. Auto-enriches leads, pushes to Notion DB, and triggers personalized outreach sequences via n8n automation workflows.',
    tags: ['Automation', 'Scraping', 'CRM'],
    tech: 'Apify · n8n · Notion API · Node.js',
    category: 'automation',
    github: 'https://github.com/namanrai1222',
    status: 'completed',
  },
];

// ─── Upcoming / Suggested Projects ───────────────────────────────────────────
export const UPCOMING_PROJECTS: UpcomingProject[] = [
  {
    id: 'brandiq',
    title: 'BrandIQ',
    description:
      'AI-powered brand audit tool. Input a company name → get full competitive analysis, brand sentiment from Twitter/Reddit, visual identity breakdown, and a 30-day growth roadmap — generated by a multi-agent LangChain pipeline.',
    tags: ['LangChain', 'Brand AI', 'NLP'],
    eta: 'Q3 2026',
    progress: 30,
  },
  {
    id: 'sentinelml',
    title: 'SentinelML',
    description:
      'Real-time misinformation monitoring dashboard. Ingests news RSS feeds, scores credibility using ensemble NLP models, and surfaces viral fake stories before they peak. Built for newsrooms and fact-checkers.',
    tags: ['NLP', 'Real-time', 'Dashboard'],
    eta: 'Q4 2026',
    progress: 15,
  },
  {
    id: 'vectorstore',
    title: 'VectorVault',
    description:
      'Open-source semantic search engine for personal knowledge bases. Upload PDFs, notes, and docs — ask questions in natural language. Powered by FastAPI, pgvector, and a local embedding model.',
    tags: ['Vector DB', 'FastAPI', 'RAG'],
    eta: 'Q4 2026',
    progress: 10,
  },
  {
    id: 'contentpilot',
    title: 'ContentPilot',
    description:
      'AI content calendar system for D2C brands. Generates 30 days of Instagram + LinkedIn posts, captions, and hooks from a brand brief. Trained on Indevaa\'s highest-performing content.',
    tags: ['LLM', 'Brand', 'Automation'],
    eta: 'Q2 2026',
    progress: 55,
  },
];

// ─── Skills ──────────────────────────────────────────────────────────────────
export const SKILLS: Skill[] = [
  // Languages
  { name: 'Python', level: 90, group: 'languages' },
  { name: 'JavaScript', level: 75, group: 'languages' },
  { name: 'SQL', level: 70, group: 'languages' },
  { name: 'PHP', level: 60, group: 'languages' },
  // ML & DS
  { name: 'Scikit-learn', level: 85, group: 'ml' },
  { name: 'Pandas / NumPy', level: 80, group: 'ml' },
  { name: 'TF-IDF / LIME', level: 80, group: 'ml' },
  // Web
  { name: 'Flask', level: 75, group: 'web' },
  { name: 'Node.js / Express', level: 70, group: 'web' },
  { name: 'REST APIs', level: 80, group: 'web' },
];

// ─── Tools ───────────────────────────────────────────────────────────────────
export const TOOLS: ToolPill[] = [
  { name: 'Git' },
  { name: 'GitHub' },
  { name: 'Docker' },
  { name: 'Apify' },
  { name: 'n8n' },
  { name: 'PostgreSQL' },
  { name: 'Postman' },
  { name: 'Jupyter' },
  { name: 'Axios' },
  { name: 'Notion API' },
  { name: 'LangChain' },
  { name: 'FastAPI' },
];

// ─── Experience ───────────────────────────────────────────────────────────────
export const EXPERIENCE: ExperienceItem[] = [
  {
    company: 'Indevaa Studio',
    role: 'Social Media & Client Manager',
    period: 'Dec 2025 – Present',
    location: 'Prayagraj',
    bullets: [
      '5+ D2C brands managed across Instagram and LinkedIn',
      'Built Apify lead pipelines — 60% reduction in manual prospecting',
      '30-day content calendars and 6-month growth roadmaps delivered',
      '10+ client contracts, proposals, service agreements written independently',
      'Short-form content: Reels scripts, carousel copy, brand captions',
    ],
  },
];

// ─── Certifications ───────────────────────────────────────────────────────────
export const CERTIFICATIONS: Certification[] = [
  { issuer: 'Oracle Academy', title: 'Database Programming with SQL' },
  { issuer: 'Infosys Springboard', title: 'Data Analytics Bundle' },
  { issuer: 'Infosys Springboard', title: 'MS SQL Server' },
  { issuer: 'Infosys Springboard', title: 'Computational Problem Solving' },
  { issuer: 'Infosys Springboard', title: 'Python Fundamentals' },
  { issuer: 'Infosys Springboard', title: 'Next Gen Technologies' },
];

// ─── Social Links ─────────────────────────────────────────────────────────────
export const SOCIAL = {
  github: 'https://github.com/namanrai1222',
  linkedin: 'https://www.linkedin.com/in/namanrai1204',
  email: 'mailto:namanrai1204@gmail.com',
  resume: '/resume.pdf',
};

// ─── Role Tags (hero orbit) ───────────────────────────────────────────────────
export const ROLE_TAGS = ['Data Scientist', 'Brand Strategist', 'NLP Builder'];

// ─── Filter Categories ────────────────────────────────────────────────────────
export const FILTER_TABS = [
  { label: 'All', value: 'all' },
  { label: 'ML', value: 'ml' },
  { label: 'Full Stack', value: 'fullstack' },
  { label: 'Automation', value: 'automation' },
] as const;

// ─── Testimonials ─────────────────────────────────────────────────────────────
export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    name: 'Client · D2C Skincare Brand',
    role: 'Founder',
    text: 'Naman mapped our entire content strategy in a week. The growth roadmap he built actually made sense — not just generic advice.',
    avatar: 'S',
  },
  {
    id: 't2',
    name: 'Client · Fashion Startup',
    role: 'Marketing Lead',
    text: 'The lead pipeline he automated saved us 15 hours a week. I didn\'t know that was even possible without a full dev team.',
    avatar: 'R',
  },
  {
    id: 't3',
    name: 'Peer · NIET Hackathon',
    role: 'Team Lead',
    text: 'His NLP pipeline was the most production-ready student project I\'ve seen. The LIME explainability layer was a genuinely clever touch.',
    avatar: 'A',
  },
];

// ─── Type declarations for new entities ──────────────────────────────────────
export interface UpcomingProject {
  id: string;
  title: string;
  description: string;
  tags: string[];
  eta: string;
  progress: number;
}

export interface Testimonial {
  id: string;
  name: string;
  role: string;
  text: string;
  avatar: string;
}
